# Generated by Django 4.1.5 on 2023-01-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назавание поля')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_head', models.BooleanField(default=False, verbose_name='Являеться ли это поле самым верхним')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назавание меню')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='FieldRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parents', to='menus.field', verbose_name='Дочернее поле')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='childs', to='menus.field', verbose_name='Родительское поле')),
            ],
            options={
                'verbose_name': 'Отношениe',
                'verbose_name_plural': 'Отношения полей меню друг к другу',
            },
        ),
        migrations.AddField(
            model_name='field',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='menus.menu', verbose_name='Меню'),
        ),
        migrations.AddConstraint(
            model_name='fieldrelations',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='unique_relation'),
        ),
    ]
